# -*- coding: utf-8 -*-
"""R4_2711

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-8IYzEWUCNafmhQgPIUT_v_1bT5cplC

Książki do R:

https://ksiegarnia.pwn.pl/Programowanie-w-jezyku-R,647767533,p.html

Na przełaj przez Data Mining z pakietem R

http://www.biecek.pl/R/

https://github.com/mim-uw/eXplainableMachineLearning-2023

https://github.com/mim-uw/MachineLearningSeminar

Zadanie 1: Napisz program tworzacy pusta macierz.
"""

mat = matrix(, nrow = 1, ncol = 1)
mat

"""Zadanie 2: Napisz program tworzacy macierz przyjmujac jako dane wejsciowe podany wektor liczb. Wyswietl macierz."""

m_vec = matrix(c(1, 2, 3, 4), 2, 2)
m_vec

"""Zadanie 3: Napisz program, ktory utworzy macierz przyjmujac jako dane wejsciowe podany wektor liczb i zdefiniuje nazwy kolumn i wierszy. Wyświetl macierz."""

colnames(m_vec) <- c("Kolumna 1", "Kolumna 2")
rownames(m_vec) <- c("Wiersz 1", "Wiersz 2")
m_vec

"""Zadanie 4: Napisz program uzyskujacy dostep do elementu w 3 kolumnie i 2 wierszu; tylko 3 wierszu i tylko 4 kolumnie danej macierzy."""

m <- matrix(1:12, nrow = 3, ncol = 4)
colnames(m) <- c("col1", "col2", "col3", "col4")
rownames(m) <- c("row1", "row2", "row3")

# Dostęp do elementu w 3 kolumnie i 2 wierszu
m[2,3]

# Dostęp tylko do 3 wierszy i 4 kolumn
m[3,4]

"""Zadanie 5: Napisz program tworzacy dwie macierze 2x3. Dodawaj, odejmij, pomnoz i podziel macierze."""

mat1 <- matrix(1:6, nrow = 2, ncol = 3)

mat2 <- matrix(7:12, nrow = 2, ncol = 3)

mat1
mat2

# Dodawanie macierzy
mat_sum <- mat1 + mat2

# Odejmowanie macierzy
mat_diff <- mat1 - mat2

# Mnozenie macierzy
mat_prod <- mat1 * mat2

# Dzielenie macierzy
mat_quot <- mat1 / mat2

# Wyswietlanie wyniku
mat_sum
mat_diff
mat_prod
mat_quot

"""Zadanie 6: Napisz program tworzacy macierz z listy podanych wektorow."""

vectors <- list(c(1, 2, 3), c(4, 5, 6), c(7, 8, 9))
matrix_from_vectors <- matrix(unlist(vectors), ncol = 3, byrow = TRUE)

matrix_from_vectors

"""Zadanie 7: Napisz program, ktory wyodrebni podmacierz, ktorej wiersze maja wartosc kolumny > 7 z danej macierzy."""

# Do poprawy, bo nie działa
m <- matrix(1:12, 4, 3)
print (m)

submatrix <- m[m[, 1] > 7, ]

print(submatrix)

"""Zadanie 8: Napisz program konwertujacy dana macierz do listy wektorow kolumnowych."""

m <- matrix(1:12, 4, 3)
column_vectors <- as.list(apply(m, 2, as.vector))

column_vectors

"""Zadanie 9: Napisz program, ktory znajdzie indeks wierszy i kolumn o wartoĹ›ci maksymalnej i minimalnej w danej macierzy."""

m <- matrix(1:12, 4, 3)
min_index <- which(m == min(m), arr.ind = TRUE)
max_index <- which(m == max(m), arr.ind = TRUE)

min_index
max_index

"""Zadanie 10: Napisz program, ktory obraca dana macierz o 90 stopni zgodnie z ruchem wskazowek zegara."""

m <- matrix(1:12, 4, 3)
rotated_matrix <- t(apply(m, 2, rev))

m
rotated_matrix

"""Zadanie 11: Napisz program konwertujacy dana macierz na tablice jednowymiarowa."""

m <- matrix(1:12, 4, 3)
arr <- as.vector(m)

arr

"""Zadanie 12: Napisz program tworzacy trojwymiarowa tablice 24 elementow za pomoca funkcji dim()."""

dim_tab <- array(1:24, dim = c(2, 3, 4))

# bez printu daje tylko ciąg znaków
print(dim_tab)

"""Zadanie 13: Napisz program tworzacy dwuwymiarowa tablice 5x3 sekwencji parzystych liczb calkowitych wiekszych niz 50."""

even_num <- seq(52, by = 2, length.out = 15)
two_dim <- matrix(even_num, 5, 3)

two_dim

"""Zadanie 14:

a) Stworz macierz o rozmiarze "30x12".

b) Poczatkowa wartosc generatora liczb pseudolosowych powinna zostac ustalona na 222.

c) Pierwsza kolumna powinna zawierac 30 unikalnych wartosci losowych z wektora "1:30".

d) Ostatnia kolumna powinna zawierac 30 nieunikalnych wartosci losowych z wektora "1:3".

e) Pozostale kolumny powinny zawierac wartosci losowe pochodzace z rozkladu rownomiernego "runif()".
"""

set.seed(222)
matrix_a <- matrix(nrow = 30, ncol = 12)

# Wypełnienie pierwszej kolumny unikalnymi wartościami z wektora 1:30
matrix_a[, 1] <- sample(1:30, 30, replace = FALSE)

# Wypełnienie ostatniej kolumny nieunikalnymi wartościami z wektora 1:3
matrix_a[, 12] <- sample(1:3, 30, replace = TRUE)

# Wypełnienie pozostałych kolumn wartościami losowymi z rozkładu rownomiernego
for (i in 2:(ncol(matrix_a)-1)) {
  matrix_a[, i] <- runif(30)
}

matrix_a