# -*- coding: utf-8 -*-
"""R5_1112

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYF-_Xpi7UBFFHT1dpFSzwl_ezLWemcD

adresy <- c("Kasztanowa 14, Bielsko Biała", "Łąki Zielonej 152, Katowice", "Specerowa 8, Elbląg")

produkty <- c("TV ", "laptop", " przenośna ładowarka", "Bezprzewodowa klawiatura", " SłuchaWki " )

dluga_sentencja <- stringr::sentences[1:10]

nazwa_pola <- c( "order_number", "order_date", "customer_email", "product_ title", "amount" )

pracownik_umiejetnosci <- c("Jan Kowalski (Beginner)", "Marta Górska (Pro)", "Krzysztof Biały (Pro)", "Sarah Machoń (Medium)")
"""

adresy <- c("Kasztanowa 14, Bielsko Biała", "Łąki Zielonej 152, Katowice", "Specerowa 8, Elbląg")
produkty <- c("TV ", "laptop", " przenośna ładowarka", "Bezprzewodowa klawiatura", " SłuchaWki " )
dluga_sentencja <- stringr::sentences[1:10]
nazwa_pola <- c( "order_number", "order_date", "customer_email", "product_ title", "amount" )
pracownik_umiejetnosci <- c("Jan Kowalski (Beginner)", "Marta Górska (Pro)", "Krzysztof Biały (Pro)", "Sarah Machoń (Medium)")

"""Zadanie 1: Normalizuj wektor adresów, zastępując wielkie litery małymi literami."""

adresy
adresy <- tolower(adresy)
adresy

"""Zadanie 2: Wybierz tylko liczbową część wektora adresów."""

adresy_liczbowe <- gsub("[^0-9]", "", adresy)
adresy_liczbowe

"""Zadanie 3: Podziel wektor adresów na dwie części: adres i miasto. Wynik powinien być macierzą."""

adresy_miasta <- strsplit(adresy, ",")
adresy_miasta <- lapply(adresy_miasta, function(x) c(x[1], x[2]))
adresy_miasta
adresy_miasta <- do.call(rbind, adresy_miasta)

adresy_miasta

"""Zadanie 4: Podziel wektor adresów na trzy części: numer domu, ulicę i miasto. Wynik powinien być macierzą. Podpowiedź: użyj asercji z wyrażeniem w tył regex."""

adresy <- c("ul. Wiejska 12", "ul. Krakowska 15", "ul. Kościuszki 20")

adresy_podzielone <- strsplit(adresy, " ")

adresy_macierz <- as.data.frame(adresy_podzielone)

colnames(adresy_macierz) <- c("Ulica", "Numer")
adresy_macierz

# Nie działa podział adresu na ulicę i numer, zapewne trzeba poprawić drugi warunek w strsplit

adresy_podzielone <- strsplit(adresy, " |, ", )
adresy_podzielone <- lapply(adresy_podzielone, function(x) c(x[2], x[1], x[3]))
adresy_podzielone <- do.call(rbind, adresy_podzielone)

adresy_podzielone

"""Zadanie 5:

W wektorze dluga_sentencja dla zdań zaczynających się na literę „T” lub kończących się na literę „s” pokaż odpowiednio pierwsze lub ostatnie słowo.

Jeśli zdanie zarówno zaczyna się na „T”, jak i kończy na „s”, pokaż zarówno pierwsze, jak i ostatnie słowo.

Pamiętaj, że faktyczny ostatni znak zdania to zwykle kropka.
"""

dluga_sentencja_zmieniona <- sapply(dluga_sentencja, function(x) {
  first_word <- strsplit(x, " ")[[1]][1]
  last_word <- strsplit(x, " ")[[1]][length(strsplit(x, " ")[[1]])]
  if (substr(x, 1, 1) == "T" & substr(last_word, nchar(last_word), nchar(last_word)) == "s") {
    paste(first_word, last_word)
  } else if (substr(x, 1, 1) == "T") {
    first_word
  } else if (substr(last_word, nchar(last_word), nchar(last_word)) == "s") {
    last_word
  } else {
    x
  }
})

dluga_sentencja_zmieniona

"""Zadanie 6: Pokaż tylko pierwszych 20 znaków wszystkich zdań w wektorze dluga_sentencja Aby wskazać, że usunąłeś niektóre znaki, użyj dwóch kolejnych kropek na końcu każdego zdania."""

dluga_sentencja_skrocone <- substr(dluga_sentencja, 1, 20)
dluga_sentencja_skrocone <- paste0(dluga_sentencja_skrocone, "..")

dluga_sentencja_skrocone

"""Zadanie 7: Znormalizuj wektor produkty, usuwając wszystkie niepotrzebne spacje (zarówno na początku, na końcu, jak i w środku) oraz używając wielkich liter."""

produkty <- gsub(" ", "", produkty)
produkty <- toupper(produkty)

# wersja rozszerzona ???
# produkty <- gsub("^\\s+|\\s+$", "", produkty)
# produkty <- gsub("\\s+", " ", produkty)


produkty

"""Zadanie 8: Przygotuj wektor nazwa_pola, zastępując wszystkie symbole podkreśleń spacjami i konwertując je na wielkie litery."""

nazwa_pola
nazwa_pola <- gsub("_", " ", nazwa_pola)
nazwa_pola <- toupper(nazwa_pola)

nazwa_pola

"""Zadanie 9: Wyrównaj wszystkie nazwa_pola, aby miały równą długość, dodając spacje na początku odpowiednich ciągów."""

max_length <- max(nchar(nazwa_pola))
max_length

# Trzeba coś poprawić w tej funkcji, gdzieś w warunku paste0 lub rep
nazwa_pola_rownej_dlugosci <- sapply(nazwa_pola, function(x) paste0(rep("-", max_length - nchar(x)), x))

print(nazwa_pola)
print(nazwa_pola_rownej_dlugosci)

"""Zadanie 10:

W wektorze pracownik_umiejetnosci poszukaj pracowników, którzy są zdefiniowani jako „Pro” lub „Medium”.

Wynikiem powinna być macierz, która zawiera imię i nazwisko pracownika w pierwszej kolumnie, a poziom umiejętności (bez nawiasów) w drugiej kolumnie.

Pracownicy, którzy nie są zakwalifikowani, powinni otrzymać brakujące wartości w obu kolumnach.
"""

# wyrażenie regularne do wyszukania poziomów "Pro" lub "Medium"
poziom_umiejetnosci <- "(Pro|Medium)"

# indeksy pracowników spełniających warunek
indeksy_pracownikow <- grep(poziom_umiejetnosci, pracownik_umiejetnosci)

# wyciągnięcie imion i nazwisk oraz poziomów umiejętności
pracownicy_wymagani <- pracownik_umiejetnosci[indeksy_pracownikow]
imiona_nazwiska <- gsub("\\s\\(.*", "", pracownicy_wymagani)
poziomy_umiejetnosci <- gsub(".*\\(|\\)", "", pracownicy_wymagani)

# utworzenie macierzy z danymi
macierz_pracownicy <- cbind(imiona_nazwiska, poziomy_umiejetnosci)

macierz_pracownicy

"""Zadanie 11:

a) Stworz wektor x zawierajacy wszystkie znaki odpowiadajace wartosciom liczbowym z zakresu 1:128.

b) Wyswietl wszystkie znaki z wektora x, ktore odpowiadaja liczbom lub literom malym lub wielkim.

c) Wyswietl wszystkie znaki z wektora x, ktore odpowiadaja liczbom lub znakom oddzielajacym tekst tj. spacja, tabulator etc.

b) Wyswietl wszystkie znaki z wektora x, ktore nie odpowiadaja liczbom.
"""

# x <- chartoRaw(as.character(1:128))
x <- as.raw(1:128)
x

# raczje źle, bo wyświetla zupełnie coś innego
x[grep("[a-zA-Z0-9]", x)]
rawToChar(x[grep("[a-zA-Z0-9]", x)])
x[grep("[0-9\\s]", x)]
rawToChar(x[grep("[0-9\\s]", x)])
x[grep("[^0-9]", x)]
rawToChar(x[grep("[^0-9]", x)])

"""Zadanie 12:

a) Stworz wektor y zawierajacy nastepujace imiona: ("Jacek", "Kasia", "Małgosia","Elżbieta","joasia").

b) Stworz wyrazenie regularne, ktore spowoduje wybranie tylko imion: "Kasia","joasia".

c) Stworz wyrazenie regularne, ktore spowoduje wybranie tylko imion: "Jacek", "Kasia".
"""

y <- c("Jacek", "Kasia", "Małgosia","Elżbieta","joasia")
y

# Można chyba pominąć "^"
y[grep("^Kasia|^joasia", y)]
y[grep("^Jacek|^Kasia", y)]

"""Zadanie 13:

a) Stwotrz obiekt "dane" na podstawie nastepujacego wektora: c("1", "1 2", "12a3", "1223", "122234", "212234","1 22 3").

b) Stworz wyrazenie regularne znajdujace elementy wektora "dane", konczace sie na "2" lub "3".

c) Stworz wyrazenie regularne znajdujace elementy wektora "dane", posiadajace od jedej do trzech "2" nie bedacych jednoczesnie poczatkiem ani koncem tekstu.

d) Stworz wyrazenie regularne znajdujace elementy wektora "dane", posiadajace male litery lub spacje.
"""

dane <- c("1", "1 2", "12a3", "1223", "122234", "212234","1 22 3")

grep("[23]$", dane, value = T)

grep("^[^2]*2[^2]*2[^2]*2?[^2]*$", dane, value = T)

grep("[a-z ]", dane, value = T)

"""Zadanie_14:

a) Stworz macierz rozmiaru "10X10" z wartosciami losowymi z rozkladu rownomiernego.

b) Stworz funkcje "Funkcja" ktora zwracac bedzie do obiektu "wynik_14" wartosc srednia dla kazdej kolumny macierzy wejsciowej.

c) Stworz "Funkcja_env" ktora bedzie "srodowiskowa" wersja powyzszej funkcji. Powinna ona nie zwracac zadnego obiektu, lecz umieszczac wynikowy obiekt w srodowisku, ktore bedzie obiektem wejsciowym dla funkcji.
"""

matrix <- matrix(runif(100), nrow = 10, ncol = 10)

Funkcja <- function(matrix) {
  wynik_14 <- apply(matrix, 2, mean)
  return(wynik_14)
}


Funkcja_env <- function(matrix) {
  assign("wynik_14", apply(matrix, 2, mean), envir = .GlobalEnv)
}

Funkcja(matrix)
wynik_14
Funkcja_env(matrix)
wynik_14
rm(wynik_14)

"""Zadanie_2:

a) Stworz srodowisko "Pierwsze".

b) Umiesc w srodowisku "Pierwsze" obiekt "x" przyjmujacy wartosc 10.

c) Stworz srodowisko "Drugie" w srodowisku "Pierwsze". (Po wyswietleniu obiektow znajdujacych sie w srodowisku "Pierwsze", srodowisko "Drugie" powinno byc tam widoczne)

d) Umiesc w srodowisku "Drugie" obiekt "y" przyjmujacy wartosc 20.

e) Stworz funkcje zamieniajaca wartosc obiektu "x" w srodowisku "Pierwsze" na warotsc z obiektu "y" ze srodowiska "Drugie". Funkcja przyjmuje jako argument srodowisko.
"""

# Nie wiem czy to w ogóle działa

adresy_miasta_ulica <- gsub("(.) (.), (.*)", "\1,\2,\3", adresy)
adresy_miasta_ulica <- strsplit(adresy_miasta_ulica, ",")
adresy_miasta_ulica <- lapply(adresy_miasta_ulica, function(x) c(x[1], x[2], x[3]))
adresy_miasta_ulica <- do.call(rbind, adresy_miasta_ulica)

adresy_miasta_ulica