# -*- coding: utf-8 -*-
"""R_2310

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXY5DmaAWuWx9B2BmREBr6wTYeN0j7H4

Zadanie 1: W konsoli oraz w skrypcie R policz 2 + 2.
"""

2+2

"""Zadanie 2: Wyswietl pomoc dla funkcji wbudowanej "print".

"""

help(print)

"""Zadanie 3: Utwórz nowy plik programu "prog_xx.R" (xx – Twoje inicjaly) i zapisz na Pulpicie, napisz polecenie wyswietlające napis 'Hello World'.

"""

print("Hello World")

"""Zadanie 4: Dodaj do siebie liczby 10 i 10. Następnie wynik podziel przez 2. Od otrzymanego wyniku odejmij 5. Następnie pomnóż wynik przez 3. Użyj nawiasów lub klamer. W wyniku ostatecznym powinna wyjsc liczba 15."""

a <- 10
b <- 10
c <- a+b
print(c)
print((c/2-5)*3) # poprawić, żeby nie pisac dwóch printów

"""Zadanie 5: Napisz na ekranie nastepujace zdanie „Poczatek jest najwazniejsza czescia pracy” – Platon. Cytat powinien byc ujety w cudzyslow."""

print(" \"Poczatek jest najwazniejsza czescia pracy\" – Platon", quote = FALSE)
cat(' "Poczatek jest najwazniejsza czescia pracy" – Platon ')

"""Zadanie 6: Napisz na ekranie w oddzielnych linijkach napis:

Nauka programowania

wymaga

wytrwałej pracy
"""

cat("Nauka programowanie \n wymaga \n wytrwałej pracy")

"""Zadanie 7: Napisz program tworzący wektor o określonym typie i dlugosci. Utwórz wektor typow numerycznych, zlozonych, logicznych i znakowych o dlugosci 10."""

num_v <- vector("integer", 10)
com_v <- vector("complex", 10)
logic_v <- vector("logical", 10)
char_v <- vector("character", 10)

num_v
com_v
logic_v
char_v 

# Też dobrze?
numeric_vector <- numeric(10)
complex_vector <- complex(10)
logical_vector <- logical(10)
character_vector <- character(10)

numeric_vector
complex_vector
logical_vector
character_vector

"""Zadanie 8: Napisz program, który doda wartosc do danego pustego wektora.

"""

x <- NULL
x <- c(x, 2)
x

"""Zadanie 9: Napisz program wyznaczajacy sume, średnia i iloczyn wektora, zignoruj elementy takie jak NA lub NaN.

"""

x <- c(1, 1, 2, 3, 5, 8, 13, 21)
sum(x, na.rm = TRUE)
mean(x, na.rm = TRUE)
prod(x, na.rm = TRUE)

"""Zadanie 10: Napisz program sortujacy wektory w porządku rosnacym i malejacym.

"""

sort(x)
sort(x, decreasing = T)

"""Zadanie 11: Napisz program znajdujacy elementy danego wektora, ktorych nie ma w innym danym wektorze.

"""

v <- c('a','b','c','e')

'b' %in% v

match('b',v)

v <- c('a','b','c','e')
z <- c('e','f','g','h')
z %in% v

match(z,v)

"""Zadanie 12: Napisz program, ktory odwroci kolejność danego wektora."""

x <- c(1, 1, 2, 3, 5, 8, 13, 21)
rev(x)

"""Zadanie 13: Napisz program tworzacy wektor, który zawiera 10 losowych liczb całkowitych z przedzialu od -10 do +10."""

x13 <- sample(-10:10, 10)
x13

"""Zadanie 14: 

a) Wysymuluj (bez powtorzen) 20 liczb calkowitych z przedzialu od 1 do 20. Poczatkowa wartosc generatora liczb pseudolosowych powinna zostac ustalona na 444.

b) Wysymuluj (bez powtorzen) 20 malych liter (alfabet podstawowy). Nie ustawiaj poczatkowej wartosci generatora liczb pseudolosowych.

c) Wyswietl wszystkie litery (pkt. b) dla ktorych liczby z odpowiadajacych indeksow z wektora numerycznego (pkt. a) sa wieksze od 5 i jednoczesnie mniejsze od 15.
"""

set.seed(444)

x20 <- sample(1:20, replace = FALSE)
length(x20)
x20

set.seed(NULL)
x_let <- sample(letters, 20, replace = FALSE)
x_let

x_let_comp <- x_let[x20 > 5 & x20 < 15]
x_let_comp

"""Zadanie 15:

a) Stworz wektor "litery" zawierajacy wielkie litery z podstawowego alfabetu (26 liter).

b) Stworz wektor "numery" zawierajacy kolejne liczby calkowite od 1 do "n", 
gdzie "n" jest liczba elementow z wektora "litery" (nie wpisujemy tej wartosci recznie).

c) Stworz wektor "litery_numery" laczacy wektory "litery" i "numery" element po elemenice poprzez znak "_".
"""

litery <- LETTERS
litery

numery <- (1:length(litery))
numery

litery_numery <- paste(litery, "_", numery)
litery_numery

"""Zadanie 16: Napisz program wybierajacy drugi element z podanej listy zagniezdzonej."""

lista <- c(1,2,3)
lista1 <- c(11,22,33)
lista2 <- c(111,222,333)
lista_nest <- list(lista,lista1,lista2)
lista_nest[[2]]

"""Zadanie 17: Napisz program, ktory utworzy liste zawierajaca wektor i liste oraz zaktualizuje ostatni element."""

wektor <- c(1,2,3)
lista <- list(4,5,6)

new_list <- list(wektor,lista)
new_list

new_list[[2]][3] <- 7
new_list

"""Zadanie 18: Napisz program, ktory scali dwie podane listy w jedna liste."""

list1 <- list(1,2,3)
list2 <- list(4,5,6)

# lub unlist(list(list1,list2))
list_c <- c(list1,list2)
list_c

"""Zadanie 19: Napisz program konwertujacy dana liste na wektor."""

lista <- list(1,2,3)

# lub new_list <- as.vector(lista)
new_list <- unlist(lista)
new_list

"""Zadanie 20: Napisz program, ktory zliczy liczbe obiektow w liscie."""

lista <- list(1, 2, 3, 4, 5, c("a", "b"), data.frame(x = 1:3, y = 4:6), TRUE)

liczba_obiektow <- sapply(lista, function(x) length(x))
liczba_obiektow

"""Zadanie 21: Napisz program, ktory przypisze wartosc NULL do danego elementu listy."""

lista <- list(1,2,3,4,5)
lista[[1]] <- NULL
lista

"""Zadanie 22: Napisz program, ktory doda 10 do kazdego elementu pierwszego wektora na podanej liscie.

"""

lista <- list(c(1:5), c(10:15), c(20:25))
lista[[1]] <- lista[[1]] + 10

lista

"""Zadanie 23: Napisz program, aby uzyskac dlugosc pierwszych dwoch wektorow z danej listy."""

lista <- list(c(1:5), c(10:15), c(20:25))
length(lista[[1]])
length(lista[[2]])

"""Zadanie 24: Napisz program, ktory znajdzie wszystkie elementy danej listy, ktorych nie ma na innej podanej liscie."""

lista1 <- list(1,2,3,4,5)
lista2 <- list(3,4,5,6)

setdiff(lista1,lista2)

"""Zadanie 25:

a) Wysymuluj z powtorzeniami 10 liczb z wektora od 1 do 10 (seed = 666).

b) Przeksztalc wektor z punktu a) na 10-elementowa liste.

c) Dla kazdego elementu listy wysumuluj "n" liczb z rozkladu rownomiernego (seed = 666), gdzie "n" jest liczba obecnie znajdujaca sie w elemencie listy.

d) Dokonaj zlaczenia elementow listy w jeden wektor.
"""

set.seed(666)

x <- sample(1:10, 10, TRUE)
x

listx <- as.list(x)
listx

for(i in 1:length(listx)){
  listx[[i]] <- runif(listx[[i]], 0, 1)
}

listx

wektor <- unlist(listx)
wektor

"""Zadanie 26:

a) Stworz liste o dlugosci 5 o wartosciach domyslnych.

b) Stworz wektor poprzez wylosowanie kolejnych 5 liczb calkowitch (bez powtorzen) z wektora od 1 do 10. Poczatkowa wartosc generatora liczb pseudolosowych powinna zostac ustalona na 123.

c) Wstaw do kolejnych elementow listy wektor powtarzajacy konkretna liczbe z wektora z pkt b) tyle razy, jaka liczba zawarta jest pod konkretnym elementem wektora, np. dla liczby 4 wektor bedzie mial dlugosc 4 i w kazdym elemencie bedzie liczba 4.

d) Przeksztalc liste w wektor liczb calkowitych.
"""

lista <- vector(mode = "list", length = 5)

set.seed(123)
v <- sample(1:10, 5, FALSE)
v

for(i in 1:length(lista)){
  lista[[i]] <- rep(v[i],v[i])
}

lista

wektor <- unlist(lista)
wektor